name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: v2.1.2
  SOLANA_VERIFY_VERSION: 0.4.4
  ARTIFACT_NAME: sol-lootbox-program.so
  DOCKER_CACHE_DIR: "$HOME/docker-cache"
  SOLANA_VERIFY_IMAGE: "solanafoundation/solana-verifiable-build@sha256:89cfdc265e1f0cb474dd18b728417830921dc11ba9138ebb26fe02ae6d53c06d"
  DOCKER_IMAGE_FILE: solana-verify-image.tgz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ env.SOLANA_VERIFY_VERSION }}
      - name: Check installed
        if: ${{ steps.cache-cargo.outputs.cache-hit == 'true' }}
        run: cargo install --list
      - name: Install solana-verify
        run: cargo install solana-verify --version ${{ env.SOLANA_VERIFY_VERSION }}

      - name: Cache docker
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: |
            "${{ env.DOCKER_CACHE_DIR }}"
            program/target
          key: ${{ runner.os }}-cargo-${{ env.SOLANA_VERIFY_IMAGE }}

      - name: Ensure cache dir exists
        run: mkdir -p "${{ env.DOCKER_CACHE_DIR }}"
      - name: Load Docker image if cached
        if: ${{ steps.cache-docker.outputs.cache-hit == 'true' }}
        run: docker load -i "${{ env.DOCKER_CACHE_DIR }}/${{ env.DOCKER_IMAGE_FILE }}"
        continue-on-error: true
      - name: Build
        run: solana-verify build "$(pwd)/program" -b "${{ env.SOLANA_VERIFY_IMAGE }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: program/target/deploy/sm.so
      - name: Cleanup key
        run: |
          echo $UID
          sudo chown -R runner program
          ls -al program/target
          find program/target
          ls -al program/target/deploy/sm-keypair.json
          rm -f program/target/deploy/sm-keypair.json
      - name: Save image if file doesn't exist
        run: |
          [ -e "${{ env.DOCKER_CACHE_DIR }}/${{ env.DOCKER_IMAGE_FILE }}" ] || docker save -o "${{ env.DOCKER_CACHE_DIR }}/${{ env.DOCKER_IMAGE_FILE }}" "${{ env.SOLANA_VERIFY_IMAGE }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}
      - name: Install solana-cli
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      - name: Prepare secrets
        run: |
          echo '${{ secrets.PROGRAM_KEY }}' > program-key.json
          echo '${{ secrets.ADMIN_KEY }}' > admin-key.json
          solana account -u ${{ vars.ENDPOINT }} program-key.json || true
          solana account -u ${{ vars.ENDPOINT }} admin-key.json || true
      - name: Deploy
        run: |
          ls -al
          solana program deploy -u ${{ vars.ENDPOINT }} -k "admin-key.json" --program-id "program-key.json" sm.so
      - name: Drop secrets
        run:
          rm -f *-key.json
  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
