name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        run: cargo install solana-verify --verbose
      - name: Build
        run: solana-verify build --mount-path program
