name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: v2.1.2
  SOLANA_VERIFY_VERSION: 0.4.4
  ARTIFACT_NAME: sol-lootbox-program.so

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ env.SOLANA_VERIFY_VERSION }}
#      - name: Cache Docker images.
#        uses: ScribeMD/docker-cache@0.5.0
#        with:
#          key: ${{ runner.os }}-docker-1
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Check installed
        if: ${{ steps.cache-cargo.outputs.cache-hit == 'true' }}
        run: cargo install --list
      - name: Install solana-verify
        run: cargo install solana-verify --version ${{ env.SOLANA_VERIFY_VERSION }}
      - name: Build
        run: solana-verify build "$(pwd)/program"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: program/target/deploy/sm.so
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}
      - name: Install solana-cli
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      - name: Prepare secrets
        run: |
          echo '${{ secrets.PROGRAM_KEY }}' > program-key.json
          echo '${{ secrets.ADMIN_KEY }}' > admin-key.json
          solana account -u ${{ vars.ENDPOINT }} program-key.json
          solana account -u ${{ vars.ENDPOINT }} admin-key.json
      - name: Deploy
        run: |
          solana program deploy -u ${{ vars.ENDPOINT }} -k "$HOME/admin-key.json" --program-id "$HOME/program-key.json" "${{ env.ARTIFACT_NAME }}"
      - name: Drop secrets
        run:
          rm -f *-key.json
  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
