name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: v2.1.2
  SOLANA_VERIFY_VERSION: 0.4.4
  ARTIFACT_NAME: sol-lootbox-program.so

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ env.SOLANA_VERIFY_VERSION }}
#      - name: Cache Docker images.
#        uses: ScribeMD/docker-cache@0.5.0
#        with:
#          key: ${{ runner.os }}-docker-1
      - name: Install solana-verify
        run: cargo install solana-verify --version ${{ env.SOLANA_VERIFY_VERSION }}
      - name: Build
        run: solana-verify build "$(pwd)/program"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: program/target/deploy/sm.so
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}
      - name: Install solana-cli
        run: sh -c "$(curl -sSfL https://release.anza.xyz/${{ env.SOLANA_VERSION }}/install)"
      - run: echo "$(pwd)/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      - name: Debug
        run: solana --version
  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
